---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022-11-11 22:11
---
-- 判断是不是自己的锁
if redis.call("get",KEYS[1]) == ARGV[1] then
    return redis.call("expire",KEYS[1],ARGV[1])
else
    return 0
end