// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
//+build !wireinject

package main


import (
	"model4/internal/biz"
	"model4/internal/data"
	"model4/internal/service"
)

// Injectors from wire.go:

func InitBmiService() *service.BmiService {


	db := data.NewDB()
	bmiRepo := data.NewBmiRepo(db)
	bmiBiz := biz.NewBmiBiz(bmiRepo)
	bmiService := service.NewBmiService(bmiBiz)
	return bmiService
}
